In [1]:
import numpy as np
import pandas as pd

In [2]:
train_df = pd.read_csv('train.csv')
train_df

id  fixed acidity  volatile acidity  citric acid  residual sugar  \
0          0            8.3              0.48         0.16             2.1   
1          1            9.8              0.29         0.34             2.1   
2          2            6.8              0.68         0.13             1.8   
3          3            8.1              0.66         0.00             2.0   
4          4            6.6              0.39         0.41             2.3   
...      ...            ...               ...          ...             ...   
14995  14995            8.2              0.60         0.27             2.2   
14996  14996            7.6              0.58         0.18             2.1   
14997  14997            7.9              0.50         0.10             2.0   
14998  14998            7.1              0.51         0.00             1.8   
14999  14999            7.2              0.61         0.01             1.9   

       chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0          0.073                  3.0                  11.0  0.99640  3.32   
1          0.076                 10.0                  24.0  0.99572  3.30   
2          0.066                 15.0                  35.0  0.99557  3.48   
3          0.087                  5.0                  13.0  0.99860  3.35   
4          0.076                 11.0                  20.0  0.99258  3.40   
...          ...                  ...                   ...      ...   ...   
14995      0.081                  6.0                  21.0  0.99580  3.22   
14996      0.066                  7.0                  24.0  0.99730  3.36   
14997      0.079                 15.0                  40.0  0.99680  3.28   
14998      0.066                  6.0                  20.0  0.99600  3.57   
14999      0.078                 14.0                  47.0  0.99498  3.47   

       sulphates  alcohol  quality  
0           0.58     10.0      5.0  
1           0.54     11.4      6.0  
2           0.60     10.7      6.0  
3           0.87      9.6      5.0  
4           0.68     10.2      5.0  
...          ...      ...      ...  
14995       0.62     10.5      6.0  
14996       0.61      9.9      5.0  
14997       0.65     10.9      6.0  
14998       0.67      9.7      6.0  
14999       0.86      9.7      5.0  

[15000 rows x 13 columns]

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id                    15000 non-null  int64  
 1   fixed acidity         15000 non-null  float64
 2   volatile acidity      15000 non-null  float64
 3   citric acid           15000 non-null  float64
 4   residual sugar        15000 non-null  float64
 5   chlorides             15000 non-null  float64
 6   free sulfur dioxide   15000 non-null  float64
 7   total sulfur dioxide  15000 non-null  float64
 8   density               15000 non-null  float64
 9   pH                    15000 non-null  float64
 10  sulphates             15000 non-null  float64
 11  alcohol               15000 non-null  float64
 12  quality               15000 non-null  float64
dtypes: float64(12), int64(1)
memory usage: 1.5 MB


In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import matplotlib.pyplot as plt

2025-06-23 10:54:14.849608: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-23 10:54:14.862647: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1750656254.875232   59279 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1750656254.878425   59279 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1750656254.893260   59279 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [41]:
from tensorflow.keras import regularizers

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
X = train_df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol' ]]

In [7]:
y = train_df[['quality']]

In [8]:
y.describe()

quality
count  15000.000000
mean       5.643933
std        0.798160
min        3.000000
25%        5.000000
50%        6.000000
75%        6.000000
max        8.000000

In [10]:
y_mod = y-3

In [11]:
y_mod.describe()

quality
count  15000.000000
mean       2.643933
std        0.798160
min        0.000000
25%        2.000000
50%        3.000000
75%        3.000000
max        5.000000

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_cv, y_train, y_cv = train_test_split(X, y, test_size = 0.3, random_state = 42 )

In [14]:
X_cv

fixed acidity  volatile acidity  citric acid  residual sugar  \
11499            7.0             0.380         0.42             2.2   
6475            10.3             0.390         0.39             2.1   
13167            7.2             0.590         0.23             1.6   
862              7.2             0.745         0.00             1.4   
5970             8.3             0.340         0.30             1.9   
...              ...               ...          ...             ...   
4217             9.8             0.240         0.49             2.1   
13886            6.4             0.620         0.14             2.4   
10464            8.3             0.580         0.33             2.1   
6902             7.9             0.390         0.11             1.9   
4874             7.5             0.600         0.26             2.7   

       chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
11499      0.095                 24.0                  72.0  0.99940  3.15   
6475       0.071                  8.0                  16.0  1.00010  3.21   
13167      0.079                 11.0                  22.0  0.99700  3.38   
862        0.086                 17.0                  40.0  0.99710  3.41   
5970       0.084                  5.0                  12.0  0.99580  3.20   
...          ...                  ...                   ...      ...   ...   
4217       0.077                 27.0                  44.0  0.99840  3.20   
13886      0.111                  6.0                  16.0  0.99590  3.38   
10464      0.073                  5.0                  15.0  0.99708  3.29   
6902       0.070                 12.0                  49.0  0.99693  3.39   
4874       0.071                 13.0                  44.0  0.99690  3.22   

       sulphates  alcohol  
11499       0.49      9.5  
6475        0.72     11.4  
13167       0.55      9.5  
862         0.71      9.7  
5970        0.81      9.3  
...          ...      ...  
4217        0.59      9.4  
13886       0.52     10.3  
10464       0.64      9.2  
6902        0.62      9.4  
4874        0.53      9.4  

[4500 rows x 11 columns]

In [15]:
y_train_mod = y_train - 3

In [16]:
y_train_mod.describe()

quality
count  10500.000000
mean       2.644000
std        0.799995
min        0.000000
25%        2.000000
50%        3.000000
75%        3.000000
max        5.000000

In [17]:
scale = StandardScaler()
X_norm = scale.fit_transform(X_train)
X_test_norm = scale.transform(X_cv)

In [52]:
model = Sequential([
    Dense(units = 120, activation = 'relu', name = "L1", kernel_regularizer = regularizers.l2(0.01) ),
    Dense(units = 100, activation = 'relu', name = "L2", kernel_regularizer = regularizers.l2(0.01)),
    Dense(units = 90, activation = 'relu', name = "L3", kernel_regularizer = regularizers.l2(0.01)),
    Dense(units = 60, activation = 'relu', name = "L4", kernel_regularizer = regularizers.l2(0.01)),
    Dense(units = 6, activation = 'linear', name = "Output")
])
model.compile(loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True), optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001))

In [53]:
model.fit(X_norm, y_train_mod, epochs = 100)

Epoch 1/100


2025-06-23 11:11:20.465353: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_299', 4 bytes spill stores, 4 bytes spill loads

2025-06-23 11:11:21.075650: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_520', 36 bytes spill stores, 36 bytes spill loads



329/329 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - loss: 2.7586  
Epoch 2/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.2258 
Epoch 3/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.1257 
Epoch 4/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.1128 
Epoch 5/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0911 
Epoch 6/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.1042 
Epoch 7/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0891 
Epoch 8/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0914 
Epoch 9/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.1014 
Epoch 10/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1.0788 
Epoch 11/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1.0804 
Epoch 12/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0681 
Epoch 13/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0860 
Epoch 14/100
329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1.0797 
Epoch 15/100
329/329 ━━━━━━━━━━━━━━━━━━━

In [54]:
test_prediction = model.predict(X_test_norm)

130/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step    

2025-06-23 11:13:32.011312: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_27', 28 bytes spill stores, 28 bytes spill loads



141/141 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step


In [55]:
test_prediction

array([[-3.4116015 , -1.3171746 ,  1.8085887 ,  1.0952555 , -1.4179109 ,
        -2.8091507 ],
       [-3.3488436 , -1.7968545 , -0.03075242,  1.0633312 ,  0.69517255,
        -1.8391505 ],
       [-3.405292  , -1.3655102 ,  1.6237681 ,  1.0923818 , -1.2052106 ,
        -2.7117128 ],
       ...,
       [-3.4062831 , -1.3558532 ,  1.6602383 ,  1.0928552 , -1.2473085 ,
        -2.7307734 ],
       [-3.4087024 , -1.3400896 ,  1.7213793 ,  1.0939537 , -1.3175573 ,
        -2.7632625 ],
       [-3.4099    , -1.3292404 ,  1.7622273 ,  1.0945046 , -1.3646754 ,
        -2.7846887 ]], dtype=float32)

In [56]:
test_pred_class = np.argmax(test_prediction, axis=1)+3

In [57]:
test_pred_class

array([5, 6, 5, ..., 5, 5, 5])

In [58]:
train_prediction = model.predict(X_norm)

329/329 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step 


In [59]:
train_pred_class = np.argmax(train_prediction, axis = 1)+3
train_pred_class

array([6, 5, 6, ..., 5, 5, 5])

In [60]:
import math
from sklearn.metrics import accuracy_score

In [61]:
print("Training accuracy ", accuracy_score(train_pred_class, y_train))
print("Cross-validation accuracy ", accuracy_score(test_pred_class, y_cv))

Training accuracy  0.5441904761904762
Cross-validation accuracy  0.5344444444444445


In [62]:
X_norm_full = scale.transform(X)
X_norm_full

array([[ 0.10331485, -0.18529432, -0.40432643, ..., -0.02144027,
        -0.36571312, -0.21657677],
       [ 1.16991047, -1.58341142,  0.6112181 , ..., -0.19276664,
        -0.73074832,  1.34482302],
       [-0.96328076,  1.2864079 , -0.57358385, ...,  1.34917069,
        -0.18319552,  0.56412312],
       ...,
       [-0.18111064, -0.0381241 , -0.74284127, ..., -0.36409301,
         0.27309847,  0.78718023],
       [-0.74996164,  0.03546102, -1.30703267, ...,  2.12013936,
         0.45561607, -0.55116244],
       [-0.67885526,  0.77131212, -1.25061353, ...,  1.26350751,
         2.18953326, -0.55116244]])

In [63]:
model.fit(X_norm_full, y_mod, epochs = 100)

Epoch 1/100
460/469 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0627

2025-06-23 11:17:03.648006: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_272', 4 bytes spill stores, 4 bytes spill loads

2025-06-23 11:17:04.018479: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_299', 28 bytes spill stores, 28 bytes spill loads

2025-06-23 11:17:04.024667: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_272', 56 bytes spill stores, 56 bytes spill loads

2025-06-23 11:17:05.676247: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_520', 36 bytes spill stores, 36 bytes spill loads

2025-06-23 11:17:05.681290: I external/local_x

469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 1.0629
Epoch 2/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.0737 
Epoch 3/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0718 
Epoch 4/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0678 
Epoch 5/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0609 
Epoch 6/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0650 
Epoch 7/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0651 
Epoch 8/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0611
Epoch 9/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0629 
Epoch 10/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0787
Epoch 11/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0711
Epoch 12/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0697
Epoch 13/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0703
Epoch 14/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0657
Epoch 15/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2m

In [66]:
pred_full = model.predict(X_norm_full)


469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [67]:
pred_full_class = np.argmax(pred_full, axis = 1) + 3
pred_full_class

array([5, 6, 6, ..., 6, 5, 5])

In [68]:
print("Accuracy score on training on full data: ", accuracy_score(pred_full_class, y))

Accuracy score on training on full data:  0.5444666666666667


In [69]:
# Now we'll be predicting for the test.cv dataset of the competition

In [70]:
test_df = pd.read_csv('test.csv')

In [71]:
test_df.head()

id  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  15000            7.1             0.735         0.00             2.3   
1  15001            6.8             0.530         0.01             2.2   
2  15002            7.1             0.715         0.12             2.0   
3  15003            8.9             0.580         0.22             2.2   
4  15004            7.6             0.620         0.03             1.7   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.064                  9.0                  23.0  0.99458  3.10   
1      0.080                  8.0                  23.0  0.99604  3.40   
2      0.077                 10.0                  22.0  0.99760  3.37   
3      0.061                  9.0                  28.0  0.99444  3.39   
4      0.081                  7.0                  31.0  0.99774  3.22   

   sulphates  alcohol  
0       0.72     11.3  
1       0.58     10.0  
2       0.63      9.7  
3       0.55     10.7  
4       0.54      9.5

In [72]:
X_test = test_df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']]

In [73]:
X_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.1             0.735         0.00             2.3      0.064   
1               6.8             0.530         0.01             2.2      0.080   
2               7.1             0.715         0.12             2.0      0.077   
3               8.9             0.580         0.22             2.2      0.061   
4               7.6             0.620         0.03             1.7      0.081   
...             ...               ...          ...             ...        ...   
9995            7.2             0.590         0.21             2.9      0.066   
9996            7.4             0.610         0.03             2.0      0.079   
9997            7.2             0.600         0.21             2.5      0.084   
9998            6.7             0.550         0.02             2.0      0.066   
9999            8.0             0.330         0.40             1.4      0.074   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                     9.0                  23.0  0.99458  3.10       0.72   
1                     8.0                  23.0  0.99604  3.40       0.58   
2                    10.0                  22.0  0.99760  3.37       0.63   
3                     9.0                  28.0  0.99444  3.39       0.55   
4                     7.0                  31.0  0.99774  3.22       0.54   
...                   ...                   ...      ...   ...        ...   
9995                 24.0                  64.0  0.99572  3.26       0.58   
9996                  6.0                  12.0  0.99590  3.38       0.65   
9997                 21.0                  98.0  0.99656  3.36       0.57   
9998                  7.0                  19.0  0.99824  3.47       0.56   
9999                  5.0                  13.0  0.99560  3.39       0.54   

      alcohol  
0        11.3  
1        10.0  
2         9.7  
3        10.7  
4         9.5  
...       ...  
9995      9.5  
9996      9.4  
9997      9.7  
9998      9.3  
9999     10.5  

[10000 rows x 11 columns]

In [74]:
X_norm_final = scale.transform(X_test)

In [75]:
X_norm_final

array([[-0.74996164,  1.69112601, -1.30703267, ..., -1.90603035,
         0.91191007,  1.23329446],
       [-0.96328076,  0.18263124, -1.25061353, ...,  0.66386521,
        -0.36571312, -0.21657677],
       [-0.74996164,  1.54395579, -0.63000299, ...,  0.40687565,
         0.09058088, -0.55116244],
       ...,
       [-0.67885526,  0.69772701, -0.12223072, ...,  0.32121247,
        -0.45697192, -0.55116244],
       [-1.03438713,  0.32980146, -1.19419439, ...,  1.26350751,
        -0.54823072, -0.99727667],
       [-0.11000427, -1.28907098,  0.94973294, ...,  0.57820203,
        -0.73074832,  0.34106601]])

In [76]:
prediction = model.predict(X_norm_final)
prediction

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step 


array([[-3.5120373 , -1.8778088 , -0.17850655,  1.0034342 ,  0.7036149 ,
        -1.8256718 ],
       [-3.442152  , -1.5655864 ,  1.2281959 ,  1.0425704 , -0.97570753,
        -2.6853144 ],
       [-3.4363027 , -1.5356768 ,  1.3638746 ,  1.0459876 , -1.1381669 ,
        -2.7687857 ],
       ...,
       [-3.423173  , -1.4559593 ,  1.7281336 ,  1.0543785 , -1.5818019 ,
        -2.996857  ],
       [-3.423749  , -1.4675975 ,  1.6726625 ,  1.0533493 , -1.511817  ,
        -2.9604437 ],
       [-3.4619632 , -1.6600678 ,  0.80261743,  1.0321747 , -0.46554115,
        -2.4242837 ]], dtype=float32)

In [77]:
prediction_class = np.argmax(prediction, axis = 1) +3 
prediction_class

array([6, 5, 5, ..., 5, 5, 6])

In [78]:
Id = test_df['id']
submission = pd.DataFrame({
    'id' : Id,
    'quality' : prediction_class.flatten()
})

In [79]:
submission.to_csv('submission.csv', index = False)